config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "islands#index"

  # Route to access islands and create bookings
  resources :islands, only: [:new, :show, :create, :destroy] do
    resources :bookings, only: [:create]
  end

  # Route to access my bookings and reviews
  resources :bookings, only: [:index] do
    resources :reviews, only: [:new, :create]
  end

  # Route to access favorites
  get '/favorites', to: 'favorites#index', as: :favorites
  # Custom routes for favorite and unfavorite actions
  post '/favorites/:id/favorite', to: 'favorites#favorite', as: :favorite_island
  delete '/favorites/:id/unfavorite', to: 'favorites#unfavorite', as: :unfavorite_island
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
  has_many :reviews, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :guest_number, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :island
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def refresh_average_rating
    self.update(average_rating: self.reviews.average(:rating).to_f.round(1))
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true

  after_create :update_island_rating

  private

  def update_island_rating
    self.booking.island.refresh_average_rating
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :islands
  has_many :bookings
  has_many :favorites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_island, only: [:create]
  before_action :authenticate_user!, only: [:create]

  def create
    @booking = Booking.new(booking_params)
    @booking.island = @island
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: "Booking was successfully created."
    end
  end

  def index
    @bookings = Booking.where(user: current_user).all
    @current_bookings = Booking.where(user: current_user).where("end_date > ?", Date.today)
    @past_bookings = Booking.where(user: current_user).where("end_date < ?", Date.today)
  end

  private

  def set_island
    @island = Island.find(params[:island_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :guest_number)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorite_islands = current_user.favorites.map { |favorite| favorite.island }
  end

  def favorite
    @island = Island.find(params[:id])
    current_user.favorites.create(island: @island)
    redirect_to root_path, notice: "#{@island.name} has been added to your favorites."
  end

  def unfavorite
    @island = Island.find(params[:id])
    favorite = current_user.favorites.find_by(island: @island)
    favorite&.destroy
    redirect_to root_path, notice: "#{@island.name} has been removed from your favorites."
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @islands = Island.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR description ILIKE :query OR location ILIKE :query"
      @islands = @islands.where(sql_subquery, query: "%#{params[:query]}%")
    end

    @markers = @islands.geocoded.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {island: island}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    @island = Island.find(params[:id])

    @marker = [
      {
        lat: @island.latitude,
        lng: @island.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {island: @island}),
        marker_html: render_to_string(partial: "marker")
      }
    ]

    @booking = Booking.new
  end

  def new
    @island = Island.new
    @my_islands = current_user.islands
  end

  def destroy
    @island = current_user.islands.find(params[:id])
    @island.destroy
    redirect_to new_island_path, notice: "Island successfully deleted."
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user

    respond_to do |format|
      if @island.save
        format.html { redirect_to island_path(@island) }
        format.json # Follows the classic Rails flow and look for a create.json view
      else
        format.html { render "island/new", status: :unprocessable_entity }
        format.json # Follows the classic Rails flow and look for a create.json view
      end
    end
  end

  private

  def island_params
    params.require(:island).permit(:name, :description, :location, :price, :capacity, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:new, :create]
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to bookings_path(@booking)
      flash[:notice] = "Review successfully created"
      @booking.island.refresh_average_rating
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">

  <h1>My current bookings</h1>
  <div class="row row-cols-1 g-4">
    <% if @current_bookings.any? %>
      <% @current_bookings.each do |booking| %>
        <div class="col">
          <%= render 'islands/card', island: booking.island %>
          <%= link_to "Add review", new_booking_review_path(booking), class: "btn btn-primary my-4" %>
          <% booking.reviews.reverse.each do |review| %>
            <%= render "/reviews/show_review", review: review %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <%= render "shared/empty_content", element: "current bookings" %>
    <% end %>
  </div>

  <h1>My past bookings</h1>
  <div class="row row-cols-1 g-4">
    <% if @past_bookings.any? %>
      <% @past_bookings.each do |booking| %>
        <div class="col">
        <%= render 'islands/card', island: booking.island %>
        <div>
        </div>
          <% unless booking.reviews.any? %>
            <%= link_to "Add review", new_booking_review_path(booking), class: "btn btn-primary" %>
          <% end %>
          <% booking.reviews.reverse.each do |review| %>
            <%= render "/reviews/show_review", review: review %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <%= render "shared/empty_content", element: "past bookings" %>
    <% end %>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="container">
  <div class="row row-cols-1 g-4">
    <h1>My favorites</h1>
    <% if @favorite_islands.any? %>
      <% @favorite_islands.each do|island|%>
        <div class="col">
          <%= render "islands/card", island: island %>
        </div>
      <% end %>
    <% else %>
      <p>You have not favorited any islands yet.</p>
    <% end %>
  </div>
</div>

app/views/islands/_card.html.erb
<div class="card-product">
  <%= link_to '', island_path(island), class: "card-link" %>
  <% if island.photos.attached? %>
    <!-- Bootstrap Carousel -->
    <div class="carousel-container">
    </div>
    <div id="carousel-<%= island.id %>" class="carousel slide" data-bs-ride="carousel">
      <!-- Carousel Items -->
      <div class="carousel-inner">
        <% island.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= 'active' if index.zero? %>">
            <%= cl_image_tag photo.key, class: "d-block w-100", alt: "Island Photo #{index + 1}" %>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= island.id %>" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= island.id %>" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <% else %>
      <div style="width: 400px; height: 300px; border: 1px dashed #ccc; display: flex; align-items: center; justify-content: center; background-color: #f9f9f9; flex-shrink: 0;">
        <span style="color: #888; font-size: 14px;">No Image Available</span>
      </div>
    <% end %>



  <div class="card-product-infos">
    <h2><%= island.name %></h2>
    <p><i class="fa-solid fa-location-dot"></i> <%= island.location %></p>
    <p><i class="fa-solid fa-bed"></i> <%= island.capacity %> guests</p>
    <p><%= island.description %></p>
    <div class="card-product-rating d-flex align-items-center">
      <% if island.average_rating %>
        <p>
          <% island.average_rating.floor.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          <% (5 - island.average_rating.floor).times do %>
            <i class="fa-regular fa-star"></i>
          <% end %>
          (<%= island.average_rating %>)
        </p>
      <% else %>
        <p>No ratings yet</p>
      <% end %>
    </div>
  </div>
  <div class="card-product-favorite">
    <% if current_user %>
      <% if params[:action] == "new" %>
        <%= link_to island_path(island), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this island?" } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      <% else %>
        <% if current_user.favorites.exists?(island: island) %>
          <%= link_to unfavorite_island_path(island), data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-heart favorite"></i>
          <% end %>
        <% else %>
          <%= link_to favorite_island_path(island), data: { turbo_method: :post } do %>
            <i class="fa-solid fa-heart"></i>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="card-product-price text-end">
    <h3>$ <%= island.price %></h3><p> per day</p>
  </div>
</div>

app/views/islands/_form.html.erb
<div class="form">
  <%= simple_form_for(@island, data: { insert_in_list_target: "form", action: "submit->insert-in-list#send" }) do |f| %>
    <%= f.input :name, label: "Island Name", input_html: { placeholder: "Enter island name" } %>
    <%= f.input :description, label: "Description", input_html: { placeholder: "Describe your island" } %>
    <div class="row">
      <div class="col-lg-6">
        <%= f.input :price, label: "Price per day ($)", input_html: { placeholder: "Enter price per day" } %>
      </div>
       <div class="col-lg-6">
        <%= f.input :capacity, label: "Capacity", input_html: { placeholder: "Enter capacity (number of people)" } %>
       </div>
    </div>
  <%= f.input :location, input_html: {data: {location_autocomplete_target: "location"}, class: "d-none"},
              wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <%= f.input :photos, as: :file, label: "Photos", input_html: { multiple: true } %>

    <%= f.submit "Create island", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/islands/_info_window.html.erb
<% if island.photos.attached? %>
<!-- Bootstrap Carousel -->
    <div id="carousel-<%= island.id %>" class="carousel slide carousel-map" data-bs-ride="carousel">
      <!-- Carousel Items -->
      <div class="carousel-inner">
        <% island.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= 'active' if index.zero? %>">
            <%= cl_image_tag photo.key,  alt: "Island Photo #{index + 1}" %>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= island.id %>" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= island.id %>" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% else %>
    <div>
    <span style="color: #888; font-size: 14px;">No Image Available</span>
    </div>
<% end %>

<div class="pop-up-content">
  <div class="pop-up-row">
  <h6><%= island.name %></h6>
  <h6><%= island.average_rating %></h6>
</div>

<p><%= island.description %></p>

<div class="pop-up-row">
  <p>$<%= island.price %>/day</p>
</div>

</div>

app/views/islands/_marker.html.erb
<%= image_tag "logo_island.png", height: 30, width: 30, alt: "Logo" %>

app/views/islands/favorites.html.erb
<h1>My favorites</h1>

<% if @favorite_islands.any? %>
  <ul>
    <% @favorite_islands.each do|island|%>
      <li>
        <p><%= island.name %></p>
        <%= link_to "View island details", island_path(island), class: "btn btn-primary", style: "margin-bottom: 16px"%>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>"You have not favorited any islands yet."</p>
<% end %>

app/views/islands/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <div class="row row-cols-1 g-4">
        <%= form_with url: root_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control bg-light",
                placeholder: "Name or location"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
        <% @islands.each do |island| %>
          <div class="col">
            <%= render 'card', island: island %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-3">
      <div class="sticky-top rounded shadow-sm"
      style="width: 100%; height: 88vh; top: 80px; z-index: 1000;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/islands/new.html.erb
<div class="container">
  <div class="row">
    <h1>Manage Your Islands</h1>
    <!-- List of Islands -->
    <div class="col" data-controller="insert-in-list">
      <div id="islands" data-insert-in-list-target="items">
        <% if @my_islands.any? %>
          <% @my_islands.each do |island| %>
            <div class="mb-4">
              <%= render "card", island: island %>
            </div>
          <% end %>
        <% else %>
          <p>You have not created any islands yet.</p>
        <% end %>
      </div>

      <!-- Toggle Form for Creating a New Island -->
      <div class="mt-5" data-controller="toggle">
        <button data-action="click->toggle#fire" class="btn btn-outline-primary">Create a new island</button>
        <div data-toggle-target="togglableElement" class="d-none mt-3">
          <%= render "form", island: @island %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/islands/show.html.erb
<div class="container mb-5">
<div class="title">
  <h1 class="my-3"><i class="fa-solid fa-umbrella-beach" style="color: #0077B6;"></i> <%= @island.name %></h1>
  <p>
    <% if @island.average_rating %>
      <% @island.average_rating.floor.times do %>
        <i class="fa-solid fa-star" style="color: #0077B6;"></i>
      <% end %>
      <% (5 - @island.average_rating.floor).times do %>
        <i class="fa-regular fa-star" style="color: #0077B6;"></i>
      <% end %>
      <%= @island.average_rating %>/5
    <% else %>
      <%= "No ratings yet." %>
    <% end %>
  </p>
</div>

  <div class="card-trip pb-3">
    <% if @island.photos.attached? %>
        <%= cl_image_tag @island.photos.first.key %>
    <% else %>
          <div style="width: 400px; height: 300px; border: 1px dashed #ccc; display: flex; align-items: center; justify-content: center; background-color: #f9f9f9;">
          <span style="color: #888; font-size: 14px;">No Image Available</span>
          </div>
    <% end %>
    <div class="card-trip-infos">
      <div>
        <h6 class="fw-bold mb-2"><i class="fa-solid fa-location-dot"></i> <%= @island.location %> guests</h6>
        <h6> <%= @island.description %></h6>
        <p class="fw-bold"><i class="fa-solid fa-bed"></i> <%= @island.capacity %> guests</p>
      </div>
      <h2 class="card-trip-pricing">$<%= @island.price %> <span class="fw-normal">per day</span></h2>
    </div>
  </div>

  <div class="row mt-3 border-top py-3">
    <div class="col-lg-8">
      <div class="rounded" style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="col-lg-4 form sticky" data-controller="toggle-booking">
      <%= simple_form_for [@island, @booking] do |f| %>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :start_date, required: true,
                                    as: :string,
                                    input_html: { data: { controller: "datepicker", toggle_booking_target: "startDate" } } %>
          </div>
          <div class="col-md-6">
            <%= f.input :end_date, required: true,
                                    as: :string,
                                   input_html: { data: { controller: "datepicker", toggle_booking_target: "endDate" } } %>
          </div>
        </div>
        <%= f.input :guest_number, required: true, input_html: { data: { toggle_booking_target: "guestNumber" } }%>
        <%= f.button :submit, "Check availability", class: "btn btn-primary w-100", data: { action: "click->toggle-booking#fire", toggle_booking_target: "button" } %>
      <% end %>
      <div data-toggle-booking-target="togglableElement" class="d-none">
        <div class="d-flex mt-3 justify-content-between">
          <p>Price per day ($)</p>
          <p data-toggle-booking-target="price"><%= @island.price %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p>Nights</p>
          <p data-toggle-booking-target="nightAmount"></p>
        </div>
        <div class="d-flex py-3 justify-content-between border-top">
          <p><strong>Total price ($)</strong></p>
          <p data-toggle-booking-target="totalPrice"></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row border-top py-3">
  <h2>Reviews</h2>
  <% @island.reviews.each_slice(2) do |reviews| %>
    <div class="row">
      <% reviews.each do |review| %>
        <div class="col-lg-6">
          <%= render "/reviews/show_review", review: review %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>SeaBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.webp') %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body class="d-flex flex-column h-100">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <main class="flex-shrink-0">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_show_review.html.erb
<div class="review bg-light p-2 my-2 shadow-sm rounded">
  <p class="fst-italic"><strong><%= review.booking.user.first_name %></strong> - <%= time_ago_in_words(review.created_at) %> ago</p>
  <% review.rating.times do %>
    <i class="fa-solid fa-star" style="color: #0077B6;"></i>
  <% end %>
  <% (5 - review.rating).times do %>
    <i class="fa-regular fa-star" style="color: #0077B6;"></i>
  <% end %>
  <p ><%= review.comment %></p>
</div>

app/views/reviews/new.html.erb
<div class="container w-50">
  <h1>Add a review for your stay at <%= @booking.island.name %></h1>
  <div class="form">
    <%= simple_form_for [@booking, @review] do |f| %>
      <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
      <%= f.input :comment, as: :text %>
      <%= f.button :submit, class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/shared/_empty_content.html.erb
<p class="fst-italic">No <%= element %> right now</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container mt-auto">
  <div class="footer d-flex  justify-content-center border-top py-3 my-4">
    <div class="footer-copyright">
      Made with <i class="fas fa-heart"></i> to all billionaires out there - SeaBnB 🌴
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon bg-dark navbar-dark shadow-sm sticky-top mb-3">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "favicon.webp" %>
      SeaBnb
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "All islands", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My favorites", favorites_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "avatar.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My islands", new_island_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>